article_id = "what-is-film"
article_title = "What is Film?"
article_contents = """
<p>
  The static site generator script is still under work so this is placeholder text I hope you're having a nice day.
</p>

<h2>Some Topic</h2>
<p>
  This topic is really cool I want to talk about it all the time.
</p>
"""

[vars]
