category_id = "film-emulation"
category_name = "Film Emulation"
category_desc = "Learning how a piece of film responds to light and how we can exploit that to capture the light."
category_visible = false
