article_id = "triangle-barycentric-coordinates"
article_title = "Triangle From Scratch 2: Inside or Outside?"
article_author = "$-blog_author-$"
article_date = "2024-04-11"
article_visible = true
article_contents = "$--load--$(\"33-triangle-barycentric-coordinates.html\")"

[vars]
