article_id = "triangle-barycentric-interpolation"
article_title = "Triangle: Interpolation"
article_author = "$-blog_author-$"
article_date = "2024-04-11"
article_visible = true
article_contents = "$--load--$(\"37-triangle-barycentric-interpolation.html\")"

[vars]
