article_id = "triangle-textured-quad"
article_title = "Triangle From Scratch 6: Textures"
article_author = "$-blog_author-$"
article_date = "2024-04-11"
article_visible = true
article_contents = "$--load--$(\"39-triangle-textured-quad.html\")"

[vars]
