article_id = "functions"
article_title = "Functions"
article_author = "$-blog_author-$"
article_date = "2024-04-11"
article_visible = true
article_contents = "$--load--$(\"48-functions.html\")"

[vars]
