category_id = "graphics-from-scratch"
category_name = "Computer Graphics From Scratch"
category_desc = "Learn how 2D/3D rendering works under the hood and how you can write your very own shaders in GLSL."
category_visible = true
