category_content_start = """
<h1 id="$--category_id--$">$--category_name--$</h1>
<h5>$--category_desc--$</h5>
"""

article_link_content = """
<p class="line-height-1-3">
<a class="link-underline-hover-only" href="$--article_path--$" target="_blank">$--article_title--$</a>
<br />
<span class="small-detail">$--article_author--$ • $--article_date_alt--$</span>
</p>
"""

category_empty_content = "<p>Stay tuned!</p>"

category_content_end = ""

[vars]
