category_content_start = """
<h1>$--category_name--$</h1>
<h5>$--category_desc--$</h5>
"""

article_link_content = """
<p class="article-link">
<a href="$--article_path--$" target="_blank">$--article_title--$</a>
<br />
<span class="small-detail">$--article_author--$ • $--article_date_alt--$</span>
</p>
"""

category_content_end = ""

[vars]
