category_content_start = """
<h1>$--category_name--$</h1>
<h5>$--category_desc--$</h5>
"""

article_link_content = """
<a href="$--article_path--$" target="_blank">$--article_title--$</a>
<br />
"""

category_content_end = "<br /><br />"

[vars]
